#!/bin/bash

# This script was generated by manually_setup_env.sh
# It sets the PYTHONPATH to include the Agno framework

# Activate the virtual environment
source "/Users/ssbedi/Desktop/pl/p-bot/backend/venv/bin/activate"

# Set PYTHONPATH to include the framework
export PYTHONPATH="/Users/ssbedi/Desktop/pl/framework/agno/libs/agno:$PYTHONPATH"

# Run the server
cd "/Users/ssbedi/Desktop/pl/p-bot/backend"
echo "Starting server with PYTHONPATH=/Users/ssbedi/Desktop/pl/framework/agno/libs/agno"
uvicorn main:app --reload
